### ISSUE TITLE
Suggestion: Consider a param and function for "remote_lookup=true"

### ISSUE THREAD

**Issue by jneubert** [Data2Semantics/prefLabel#2]
I learned about preflabel.org through Laurens Rietveld's YASR library, and like the idea of an efficient central access to labels for resources very much.
However, there is one downside: preflabel.org currently supports 3 data sources, and unfortunately none of mine :(. Of course, trying to add small datasets like [STW Thesaurus for Economics](http://zbw.eu/stw) to such a service upon request and keeping up with new versions would cause a maintenance nightmare.
This could be mitigated by an API parameter and a function for `remote_lookup`, which would execute a linked data lookup of the URI, and try to pull out something like a label (skos:prefLabel, dc:title, foaf:name, …, down to rdfs:label). 
This would not be as fast as originally intended by the service, but it could work for almost every linked data source. I think, for YASR/YASGUI and similar use cases a slower remote lookup would be fine, and the benefits could be immense: preflabel.org would a) work as a central proxy and perhaps cache for widespread sources, and b) encapsulate the preflabel extraction logic (with an ever growing list of "preflabel candidate" properties, and perhaps some discussion and decisions about precedence) in one central location.
In the future, the service could be transparently extended with some passive or active caching strategies for frequently used data soures.
What do you think?

**Comment by cmarat** [comment]
The idea makes a lot of sense, and I'd love to see this implemented as a separate application which can be integrated with prefLabel service. Besides attempting to dereference unknown resources, it might also query public SPARQL endpoints such as the LOD Cache. 

As to getting labels into prefLabel for fast access, consider submitting a link to your dataset to http://lodlaundromat.org/basket/. In the nearest future we want to start loading labels from there. This will only work for entities which share domain name with the source of the dataset.
